name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Gebruik npm install i.p.v. npm ci voor tolerantere installs
      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Lint (if present)
        run: npm run lint --if-present

      - name: Typecheck (if present)
        run: npm run typecheck --if-present

      - name: Build
        run: npm run build

      - name: Dry-run generate workouts (small)
        run: npx tsx scripts/build/build-workout-library.ts --target=50 --chunk=25

      - name: Dry-run import mapping (no Supabase)
        run: npx tsx scripts/deploy/import-workouts-to-db.ts public/data/workouts --dry-run
